config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'organisations#index'
  resources :organisations do
    resources :organisation_enrollments, only: :create
    resources :shifts, only: [:update, :index]
  end

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :shifts
  has_many :organisation_enrollments
  
end

app/models/organisation_enrollment.rb
class OrganisationEnrollment < ApplicationRecord
  belongs_to :organisation
  belongs_to :user
  has_many :shifts

end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :organisation_enrollments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :organisation_enrollments
  has_many :joined_organisations, through: :organisation_enrollments, source: :organisation

  def joined_organisation?(organisation)
    joined_organisations = organisation_enrollments.collect(&:organisation)
    return joined_organisations.include?(organisation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

     devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
    end
end

app/controllers/organisation/shifts_controller.rb
class ShiftsController < OrganisationsController
  before_action :authenticate_user!
  before_action :current_organisation

  def index
    @current_organisation.shifts
  end

  def update

  end

  def new
    @shift = Shift.new
  end

  def create
    @current_organisation.shifts.create(shift_params)
    redirect_to organisation_shifts_path(@organisation)
  end

  private
  def shift_params
    params.require(:shift).permit(:start, :finish, :break_length, :organisation_enrollment_id)
  end

  def current_organisation
    @current_organisation ||= Organisation.find(params[:organisation_id])
  end

end

app/controllers/organisation_enrollments_controller.rb
class OrganisationEnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.organisation_enrollments.create(organisation: current_organisation)
    redirect_to organisation_path(current_organisation)
  end

  private

  def current_organisation
    @current_organisation ||= Organisation.find(params[:organisation_id])
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @organisations = Organisation.all
    @organisation = Organisation.new
  end

  def show
    @organisation = Organisation.find(params[:id])
  end
  def new

  end

  def create
    @organisation = Organisation.create(organisation_params)
  end

  def edit
    @organisation = Organisation.find(params[:id])
  end

  def update
    @organisation = Organisation.find(params[:id])

    if current_user.present
      @organisation.update(organisation_params)
      redirect_to root_path
    else
      @current_organisation.update(organisation_params)
      redirect_to user_path
    end

  end

  private
  def organisation_params
    params.require(:organisation).permit(:name, :hourly_rate, :user_id)
  end

  def current_organisation
    @current_organisation ||= Organisation.find(params[:id])
  end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

  def index
    @shift = Shift.all
  end

  def update

  end

  private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
    @user = User.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organisation_enrollments_helper.rb
module OrganisationEnrollmentsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adnat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <h1 class="center"><%= link_to 'Adnat Time App', root_path, class: 'clean blue' %></h1>
    <div class="right-align">
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    </div>
    

    <%= yield %>
  </body>
</html>

app/views/organisations/edit.html.erb
<div class="box">
  <div class="center">
    <h3 class="blue">Edit <%= @organisation.name %></h3>
    <%= simple_form_for @organisation do |f| %>
      <br />
      <%= f.input :name, label: 'Name: ', label_html: { class: 'field' } %>
      <br />
      <%= f.input :hourly_rate, label: 'Hourly Rate: ', label_html: { class: 'field' }  %>
      <br />
      <%= f.submit 'Update', method: :put, class: 'field button border' %>
      <%= link_to 'Cancel', organisations_path(@organisation), class: 'button border' %>
      <br /><br />
    <% end %>
  </div>
</div>

app/views/organisations/index.html.erb
<div class="box">
  <p class="center">Signed in as <%= current_user.name %></p>

  <h4 class="left-align">To get started you need to join or create an Organisation</h4>

  <h3 class="blue center">Organisations</h3>
  <ul class="left-align">
    <% @organisations.each do |item| %>
      <li><%= item.name %>
        <%= link_to 'Edit', edit_organisation_path(item) %>
        <% if current_user.joined_organisation?(item) %>
          <p>You are a member of this organisation</p>
        <% else %>
          <%= link_to 'Join', organisation_organisation_enrollments_path(item), method: :post %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <h3 class="blue center">Create an Organisation</h3>
  <div class="left-align field">
    <%= simple_form_for @organisation do |f| %>
      <%= f.input :name, label: 'Name:', label_html: { class: 'form_field field' } %>
      <%= f.input :hourly_rate, label: 'Hourly Rate:', label_html: { class: 'form_field field' } %>
      <%= f.button :submit, class: 'field blue', style: 'margin-bottom: 15px;' %>
    <% end %>
  </div>
</div>

<script>
  function joinOrganisation(id) {
    console.log(id.inspect);
    return new Promise((resolve, reject) => {
      this.$http.put(`/organisations/3`, {
        organisation: {
          user_id: id
        }
      })
      .then((response) => {
        alert("Organisation Joined")
        });
        resolve(response);
      })
  }
</script>

app/views/organisations/show.html.erb
<div  class="box">
  <h3 class="center blue"><%= @organisation.name %></h3>
  <div class="center" style="margin: 10px;">
    <%= link_to 'View Shifts', organisation_shifts_path(@organisation), class: 'border' %>
    <%= link_to 'Edit', edit_organisation_path(@organisation), class: 'border' %>
    <%= link_to 'Leave Organisation', organisation_organisation_enrollments_path(@organisation), class: 'border', method: :destroy %>
  </div>


</div>

app/views/shifts/index.html.erb
<h3> View showing shifts for a given account </h3>

<table style="width:80%" class="center">
  <tr>
    <th>Employee Name</th>
    <th>Shift Date</th>
    <th>Start Time</th>
    <th>Finish Time</th>
    <th>Break Length (minutes)</th>
    <th>Hours Worked</th>
    <th>Shift Cost</th>
  </tr>
  <%= @shifts.each do |shift| %>
    <tr>
      <td><%= shift.user.name %></td>
      <td><%= shift.user.name %></td>
      <td><%= shift.user.name %></td>
      <td><%= shift.user.name %></td>
      <td><%= shift.user.name %></td>
      <td><%= shift.user.name %></td>
      <td><%= shift.user.name %></td>
    </tr>
  <% end %>
</table>

app/views/users/index.html.erb
<h2> Hello User</h2>

app/views/users/show.html.erb
<h2>Test page</h2>